apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: traccar
spec:
  template:
    spec:
      containers:
        - image: gcr.io/ave-asistencia-vehicular/traccar-custom:latest
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: traccar-secrets
                  key: db-host
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: traccar-secrets
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: traccar-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: traccar-secrets
                  key: db-password
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
