steps:
  # (tus pasos de compilación existentes)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/TU_PROJECT_ID/traccar-custom:latest', '.']
    # O para Artifact Registry:
    # args: ['build', '-t', 'TU_REGION-docker.pkg.dev/TU_PROJECT_ID/TU_REPOSITORIO/traccar-custom:latest', '.']

images:
  # (tus imágenes existentes)
  - 'gcr.io/TU_PROJECT_ID/traccar-custom:latest'
  # O para Artifact Registry:
  # - 'TU_REGION-docker.pkg.dev/TU_PROJECT_ID/TU_REPOSITORIO/traccar-custom:latest'

# 👇 AÑADE O DESCOMENTA ESTA SECCIÓN
options:
  logging: CLOUD_LOGGING_ONLY
