steps:
  # Paso de depuración (puedes eliminarlo si ya no lo necesitas)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Contenido de /workspace/:" && ls -la /workspace/'

  # Paso de construcción de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ave-asistencia-vehicular/traccar-custom:latest', '.'] # USA TU ID DE PROYECTO REAL AQUÍ

images:
  - 'gcr.io/ave-asistencia-vehicular/traccar-custom:latest' # Y AQUÍ TAMBIÉN

options:
  logging: CLOUD_LOGGING_ONLY
