steps:
  # 1. Construye la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/TU_PROJECT_ID/traccar-custom:latest', '.']
    # Descomenta la siguiente línea si prefieres usar Artifact Registry:
    # args: ['build', '-t', 'TU_REGION-docker.pkg.dev/TU_PROJECT_ID/TU_REPOSITORIO/traccar-custom:latest', '.']

  # 2. Sube la imagen Docker construida
  # Para GCR:
images:
  - 'gcr.io/TU_PROJECT_ID/traccar-custom:latest'

# Para Artifact Registry (asegúrate de que el repositorio exista):
# images:
#  - 'TU_REGION-docker.pkg.dev/TU_PROJECT_ID/TU_REPOSITORIO/traccar-custom:latest'

# Opciones (opcional):
# options:
#   logging: CLOUD_LOGGING_ONLY
